version: "3.4"

services:
  vite-app:
    image: node:alpine
    container_name: vite-app-container
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
