name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install -g yarn && yarn install

      - name: Lint
        run: yarn lint

      - name: Build package & docs
        run: yarn build:all
